
services:
  node-app:
    image: node:22-alpine
    container_name: node-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    networks:
      - app-dev-network
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true  # 文件监听


networks:
  app-dev-network:
    driver: bridge