server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:mysql://localhost:3306/ai_agent_db
    username: root
    password: chenhao20030210
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.project.module.*.entity

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTBhYmNkZWYxMjM0NTY3ODkwYWJjZGVm}
  expiration: 86400000
  header: Authorization
  prefix: Bearer
